server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/goliva-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/